quiz_project/quiz_project/urls.py
from django.urls import path, include
from django.contrib import admin

from quiz_app import views
from django.contrib.auth.views import LogoutView, LoginView




urlpatterns = [
   
    path('admin/', admin.site.urls),
    path('teacher/',include('teacher.urls')),
    path('student/',include('student.urls')),
    
    
    

###dashboardddd
    path('',views.home_view,name=''),
    path('logout', LogoutView.as_view(template_name='logout.html'),name='logout'),
    path('aboutus', views.aboutus_view),
    path('contactus', views.contactus_view),
    path('afterlogin', views.afterlogin_view,name='afterlogin'),


#####admin board    
    path('adminclick', views.adminclick_view),
    path('adminlogin', LoginView.as_view(template_name='adminlogin.html'),name='adminlogin'),
    path('admin-dashboard', views.admin_dashboard_view,name='admin-dashboard'),
    path('admin-teacher', views.admin_teacher_view,name='admin-teacher'),
    path('admin-view-teacher', views.admin_view_teacher_view,name='admin-view-teacher'),
    path('update-teacher/<int:pk>', views.update_teacher_view,name='update-teacher'),
    path('delete-teacher/<int:pk>', views.delete_teacher_view,name='delete-teacher'),
    path('admin-view-pending-teacher', views.admin_view_pending_teacher_view,name='admin-view-pending-teacher'),
    path('admin-view-teacher-salary', views.admin_view_teacher_salary_view,name='admin-view-teacher-salary'),
    path('approve-teacher/<int:pk>', views.approve_teacher_view,name='approve-teacher'),
    path('reject-teacher/<int:pk>', views.reject_teacher_view,name='reject-teacher'),

 ##admin view student
    path('admin-student', views.admin_student_view,name='admin-student'),
    path('admin-view-student', views.admin_view_student_view,name='admin-view-student'),
    path('admin-view-student-marks', views.admin_view_student_marks_view,name='admin-view-student-marks'),
    path('admin-view-marks/<int:pk>', views.admin_view_marks_view,name='admin-view-marks'),
    path('admin-check-marks/<int:pk>', views.admin_check_marks_view,name='admin-check-marks'),
    path('update-student/<int:pk>', views.update_student_view,name='update-student'),
    path('delete-student/<int:pk>', views.delete_student_view,name='delete-student'),

 ##admin view course
    path('admin-course', views.admin_course_view,name='admin-course'),
    path('admin-add-course', views.admin_add_course_view,name='admin-add-course'),
    path('admin-view-course', views.admin_view_course_view,name='admin-view-course'),
    path('delete-course/<int:pk>', views.delete_course_view,name='delete-course'),
##admin view question
    path('admin-question', views.admin_question_view,name='admin-question'),
    path('admin-add-question', views.admin_add_question_view,name='admin-add-question'),
    path('admin-view-question', views.admin_view_question_view,name='admin-view-question'),
    path('view-question/<int:pk>', views.view_question_view,name='view-question'),
    path('delete-question/<int:pk>', views.delete_question_view,name='delete-question'),


]

student/urls.py
from django.urls import path
from student import views
from django.contrib.auth.views import LoginView

app_name="student"

urlpatterns = [
path('studentclick/', views.studentclick_view),
path('studentlogin/', LoginView.as_view(template_name='studentlogin.html'),name='studentlogin'),
path('signup/', views.student_signup_view,name='studentsignup'),

path('student-dashboard/', views.student_dashboard_view, name='student-dashboard'),

path('student-exam/', views.student_exam_view,name='student-exam'),
path('take-exam/<int:pk>/', views.take_exam_view,name='take-exam'),
path('start-exam/<int:pk>/', views.start_exam_view, name='start-exam'),


path('calculate-marks/', views.calculate_marks_view, name='calculate_marks'),
 path('view-result/', views.view_result_view, name='view_result'), 
path('check-marks/<int:pk>/', views.check_marks_view, name='check-marks'),
path('student-marks/', views.student_marks_view,name='student-marks'),
]       

teacher/urls.py
from django.urls import path
from teacher import views
from django.contrib.auth.views import LoginView

app_name="teacher"
urlpatterns = [
path('teacherclick/', views.teacherclick_view),
path('teacherlogin/', LoginView.as_view(template_name='teacherlogin.html'),name='teacherlogin'),
path('signup/', views.teacher_signup_view, name='teachersignup'),   

path('teacher-dashboard/', views.teacher_dashboard_view,name='teacher-dashboard'),
path('teacher-exam/', views.teacher_exam_view,name='teacher-exam'),
path('teacher-add-exam/', views.teacher_add_exam_view,name='teacher-add-exam'),
path('teacher-view-exam/', views.teacher_view_exam_view,name='teacher-view-exam'),
path('delete-exam/<int:pk>/', views.delete_exam_view,name='delete-exam'),


path('teacher-question/', views.teacher_question_view,name='teacher-question'),
path('teacher-add-question/', views.teacher_add_question_view,name='teacher-add-question'),
path('teacher-view-question/', views.teacher_view_question_view,name='teacher-view-question'),
path('see-question/<int:pk>/', views.see_question_view,name='see-question'),
path('remove-question/<int:pk>/', views.remove_question_view,name='remove-question'),
]

teacher/models.py
from django.db import models
from django.contrib.auth.models import User



class Teacher(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    profile_pic= models.ImageField(upload_to='profile_pic/Teacher/',null=True,blank=True)
    address = models.CharField(max_length=40)
    mobile = models.CharField(max_length=20,null=False)
    status= models.BooleanField(default=False)
    salary=models.PositiveIntegerField(null=True)
    @property
    def get_name(self):
        return self.user.first_name+" "+self.user.last_name
    @property
    def get_instance(self):
        return self
    def __str__(self):
        return self.user.first_name

teacher/forms.py
from django import forms
from django.contrib.auth.models import User
from . import models

class TeacherUserForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['first_name','last_name','username','password']
        widgets = {
        'password': forms.PasswordInput()
        }

class TeacherForm(forms.ModelForm):
    class Meta:
        model=models.Teacher
        fields=['address','mobile','profile_pic']

teacher/views.py
from django.shortcuts import render,redirect,reverse
from . import forms,models
from django.db.models import Sum
from django.contrib.auth.models import Group
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required,user_passes_test
from django.conf import settings
from datetime import date, timedelta
from quiz_app.models import Course, Question
from student.models import Student
from quiz_app import forms as QFORM

#for showing signup/login button for teacher
def teacherclick_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('afterlogin'))

    return render(request,'teacherclick.html')

def teacher_signup_view(request):
    userForm=forms.TeacherUserForm()
    teacherForm=forms.TeacherForm()
    mydict={'userForm':userForm,'teacherForm':teacherForm}
    if request.method=='POST':
        userForm=forms.TeacherUserForm(request.POST)
        teacherForm=forms.TeacherForm(request.POST,request.FILES)
        if userForm.is_valid() and teacherForm.is_valid():
            user=userForm.save()
            user.set_password(user.password)
            user.save()
            teacher=teacherForm.save(commit=False)
            teacher.user=user
            teacher.save()
            my_teacher_group = Group.objects.get_or_create(name='TEACHER')
            my_teacher_group[0].user_set.add(user)
        return HttpResponseRedirect(reverse('teacher:teacherlogin'))

    return render(request, 'teachersignup.html', context=mydict)




def is_teacher(user):
    return user.groups.filter(name='TEACHER').exists()

@login_required(login_url='teacherlogin')
@user_passes_test(is_teacher)
def teacher_dashboard_view(request):
    dict={
    
    'total_course':Course.objects.all().count(),
    'total_question':Question.objects.all().count(),
    'total_student':Student.objects.all().count()
    }
    return render(request,'teacher_dashboard.html',context=dict)




@login_required(login_url='teacherlogin')
@user_passes_test(is_teacher)
def teacher_exam_view(request):
    return render(request,'teacher_exam.html')





@login_required(login_url='teacherlogin')
@user_passes_test(is_teacher)
def teacher_add_exam_view(request):
    courseForm=QFORM.CourseForm()
    if request.method=='POST':
        courseForm=QFORM.CourseForm(request.POST)
        if courseForm.is_valid():        
            courseForm.save()
        else:
            print("form is invalid")
        return HttpResponseRedirect('/teacher/teacher-view-exam')
    return render(request,'teacher_add_exam.html',{'courseForm':courseForm})




@login_required(login_url='teacherlogin')
@user_passes_test(is_teacher)
def teacher_view_exam_view(request):
    courses = Course.objects.all()
    return render(request,'teacher_view_exam.html',{'courses':courses})




@login_required(login_url='teacherlogin')
@user_passes_test(is_teacher)
def delete_exam_view(request,pk):
    course=Course.objects.get(id=pk)
    course.delete()
    return HttpResponseRedirect('/teacher/teacher-view-exam')




@login_required(login_url='adminlogin')
def teacher_question_view(request):
    return render(request,'teacher_question.html')




@login_required(login_url='teacherlogin')
@user_passes_test(is_teacher)
def teacher_add_question_view(request):
    questionForm=QFORM.QuestionForm()
    if request.method=='POST':
        questionForm=QFORM.QuestionForm(request.POST)
        if questionForm.is_valid():
            question=questionForm.save(commit=False)
            course=Course.objects.get(id=request.POST.get('courseID'))
            question.course=course
            question.save()       
        else:
            print("form is invalid")
        return HttpResponseRedirect('/teacher/teacher-view-question')
    return render(request,'teacher_add_question.html',{'questionForm':questionForm})




@login_required(login_url='teacherlogin')
@user_passes_test(is_teacher)
def teacher_view_question_view(request):
    courses= Course.objects.all()
    return render(request,'teacher_view_question.html',{'courses':courses})




@login_required(login_url='teacherlogin')
@user_passes_test(is_teacher)
def see_question_view(request,pk):
    questions=Question.objects.all().filter(course_id=pk)
    return render(request,'see_question.html',{'questions':questions})




@login_required(login_url='teacherlogin')
@user_passes_test(is_teacher)
def remove_question_view(request,pk):
    question=Question.objects.get(id=pk)
    question.delete()
    return HttpResponseRedirect('/teacher/teacher-view-question')

teacher/templates/see_question.html
{% extends 'teacherbase.html' %}
{% block content %}
{%load static%}

<head>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

  <style media="screen">
    a:link {
      text-decoration: none;
    }

    h6 {
      text-align: center;
    }

    .row {
      margin: 100px;
    }
  </style>
</head>
<br><br>
<div class="container">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h6 class="panel-title">Questions</h6>
    </div>
    <table class="table table-hover" id="dev-table">
      <thead>
        <tr>

          <th>Question</th>
         
          <th>Marks</th>
          <th>Delete Question</th>
        </tr>
      </thead>
      {% for c in questions %}
      <tr>

        <td> {{c.question}}</td>
        
        <td>{{c.marks}}</td>
        <td><a class="btn btn-primary btn-xs" href="{% url 'teacher:remove-question' c.id  %}"><span class="glyphicon glyphicon-trash"></span></a></td>
        
      </tr>
      {% endfor %}
    </table>
  </div>
</div>

<br><br><br><br><br><br>
{% endblock content %}

teacher/templates/teacher_add_exam.html
{% extends 'teacherbase.html' %}
{% load widget_tweaks %}
{% block content %}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
      a:link {
        text-decoration: none;
      }
    </style>
</head>
<h2 style="text-align:center; color:blue;">ADD EXAM</h2>
<form method="POST" autocomplete="off" style="margin:100px;margin-top: 0px;">
    {% csrf_token %}
    <div class="form-group">
        <label for="course_name">Exam Name</label>
        {% render_field courseForm.course_name class="form-control" placeholder="Exam Name" %}

        <label for="question_number">Total Question</label>
        {% render_field courseForm.question_number class="form-control" placeholder="10" %}

        <label for="total_marks">Total Marks</label>
        {% render_field courseForm.total_marks class="form-control" placeholder="50" %}
    </div>

    <button type="submit" class="btn btn-primary">ADD</button>
</form>
<br><br><br>
{% endblock content %}

teacher/templates/teacher_exam.html
{% extends 'teacherbase.html' %}
{% load widget_tweaks %}
{% block content %}


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <link href="http://netdna.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <style type="text/css">
      a:link {
        text-decoration: none;
      }
  
      .order-card {
        color: rgb(255, 255, 255);
      }
  
      .bg-c-blue {
        background: #04868f;
      }
  
      .bg-c-green {
        background:#4C51BF;
      }
  
      .bg-c-yellow {
        background: #F56565;
      }
  
      .bg-c-pink {
        background: #663a30;
      }
  
  
      .card {
        
        -webkit-box-shadow: 0 1px 2.94px 0.06px rgba(4, 26, 55, 0.16);
        box-shadow: 0 1px 2.94px 0.06px rgba(4, 26, 55, 0.16);
        border: 1px solid black;
        margin-bottom: 30px;
        -webkit-transition: all 0.3s ease-in-out;
        transition: all 0.3s ease-in-out;
      }
  
      .card .card-block {
        padding: 25px;
      }
  
      .order-card i {
        font-size: 26px;
      }
  
      .f-left {
        float: left;
      }
  
      .f-right {
        float: right;
      }
      header {
      left: 0px;
      right: 0px;
    }
    </style>
  </head>
<br><br>

  <div class="container">
    <div class="row">
      <div class="col-md-4 col-xl-6">
        <div class="card bg-c-blue order-card">
          <div class="card-block">
            <h6 class="m-b-20"><a href="{% url 'teacher:teacher-add-exam' %}" style="text-decoration: none;color:white;">Add Exam</a></h6>
            <h2 class="text-right"><i class="fas fa-plus f-left"></i></h2>
            
          </div>
        </div>
      </div>
  
      <div class="col-md-4 col-xl-6">
        <div class="card bg-c-green order-card">
          <div class="card-block">
            <h6 class="m-b-20"><a href="{% url 'teacher:teacher-view-exam' %}" style="text-decoration: none;color:white;">View Exams</a></h6>
            <h2 class="text-right"><i class="fas fa-eye f-left"></i></h2>
            
          </div>
        </div>
      </div>
  
     
  
     
    </div>
  </div>


<br><br><br><br><br><br><br><br><br><br>

<script src="http://netdna.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>


{% endblock content %}

teacher/templates/teacher_question.html
{% extends 'teacherbase.html' %}
{% load widget_tweaks %}
{% block content %}


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <link href="http://netdna.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <style type="text/css">
      a:link {
        text-decoration: none;
      }
  
      .order-card {
        color: rgb(255, 255, 255);
      }
  
      .bg-c-blue {
        background: #04868f;
      }
  
      .bg-c-green {
        background:#4C51BF;
      }
  
      .bg-c-yellow {
        background: #F56565;
      }
  
      .bg-c-pink {
        background: #663a30;
      }
  
  
      .card {
        
        -webkit-box-shadow: 0 1px 2.94px 0.06px rgba(4, 26, 55, 0.16);
        box-shadow: 0 1px 2.94px 0.06px rgba(4, 26, 55, 0.16);
        border: 1px solid black;
        margin-bottom: 30px;
        -webkit-transition: all 0.3s ease-in-out;
        transition: all 0.3s ease-in-out;
      }
  
      .card .card-block {
        padding: 25px;
      }
  
      .order-card i {
        font-size: 26px;
      }
  
      .f-left {
        float: left;
      }
  
      .f-right {
        float: right;
      }
      header {
      left: 0px;
      right: 0px;
    }
    </style>
  </head>
<br><br>

  <div class="container">
    <div class="row">
      <div class="col-md-4 col-xl-6">
        <div class="card bg-c-blue order-card">
          <div class="card-block">
            <h6 class="m-b-20"><a href="{% url 'teacher:teacher-add-question' %}" style="text-decoration: none; color: white;">Add Question</a></h6>

            <h2 class="text-right"><i class="fas fa-plus f-left"></i></h2>
            
          </div>
        </div>
      </div>
  
      <div class="col-md-4 col-xl-6">
        <div class="card bg-c-green order-card">
          <div class="card-block">
            <h6 class="m-b-20"><a href="{% url 'teacher:teacher-view-question' %}" style="text-decoration: none;color:white;">View Questions</a> </h6>
            <h2 class="text-right"><i class="fas fa-eye f-left"></i></h2>
            
          </div>
        </div>
      </div>
  
     
  
     
    </div>
  </div>


<br><br><br><br><br><br><br><br><br><br>

<script src="http://netdna.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>


{% endblock content %}

teacher/templates/teacher_view_exam.html
{% extends 'teacherbase.html' %}
{% block content %}
{%load static%}

<head>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

  <style media="screen">
    a:link {
      text-decoration: none;
    }

    h6 {
      text-align: center;
    }

    .row {
      margin: 100px;
    }
  </style>
</head>
<br><br>
<div class="container">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h6 class="panel-title">Exams</h6>
    </div>
    <table class="table table-hover" id="dev-table">
      <thead>
        <tr>

          <th>Course Name</th>
          <th>Total Question</th>
          <th>Total Marks</th>
          <th>Delete</th>
        </tr>
      </thead>
      {% for t in courses %}
      <tr>

        <td> {{t.course_name}}</td>
        <td>{{t.question_number}}</td>
        <td>{{t.total_marks}}</td>
        
        <td><a class="btn btn-danger btn-xs" href="{% url 'teacher:delete-exam' t.id %}"><span class="glyphicon glyphicon-trash"></span></a></td>

      </tr>
      {% endfor %}
    </table>
  </div>
</div>

<br><br><br><br><br><br>
{% endblock content %}

teacher/templates/teacher_view_question.html
{% extends 'teacherbase.html' %}
{% block content %}
{%load static%}

<head>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

  <style media="screen">
    a:link {
      text-decoration: none;
    }

    h6 {
      text-align: center;
    }

    .row {
      margin: 100px;
    }
  </style>
</head>
<br><br>
<div class="container">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h6 class="panel-title">Select Course To View Questions</h6>
    </div>
    <table class="table table-hover" id="dev-table">
      <thead>
        <tr>

          <th>Course Name</th>
          <th>Total Question</th>
          <th>Total Marks</th>
          <th>View Question</th>
        </tr>
      </thead>
      {% for c in courses %}
      <tr>

        <td> {{c.course_name}}</td>
        <td>{{c.question_number}}</td>
        <td>{{c.total_marks}}</td>
        <td><a class="btn btn-primary btn-xs" href="{% url 'teacher:see-question' c.id  %}"><span class="glyphicon glyphicon-eye-open"></span></a></td>

        
      </tr>
      {% endfor %}
    </table>
  </div>
</div>

<br><br><br><br><br><br>
{% endblock content %}

teacher/templates/teacher_wait_for_approval.html
<!DOCTYPE html>
{% load widget_tweaks %}


  <style media="screen">
    .jumbotron {
      margin-top: 0px;
      margin-bottom: 0px;
    }

    .jumbotron h1 {
      text-align: center;
    }

    .alert {
      margin: 0px;
    }
  </style>
  <body>
    {% include "navbar.html" %}

      <div class="jumbotron" style="margin-top: 0px;
        margin-bottom: 0px;">
        <h1 class="display-4">Hello {{request.user.first_name}}</h1>
        <p class="lead">Your Account is not approved  now <br><br> <br><br> Account Will Be Approved Soon</p>
        <hr class="my-4">
        <p>Check Later</p>
        <p class="lead">
          <a class="btn btn-primary btn-lg" href="logout" role="button">Logout For Now</a>
        </p>
      </div>

{% include "footer.html" %}
  </body>
</html>

teacher/templates/teacherbase.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
 

  <style media="screen">
    a:link {
      text-decoration: none;
    }

    body {
      margin: 0;
      padding: 0;
      font-family: "Gill Sans", sans-serif;;
    }

    header {
      position: fixed;
      background: #497a49;
      padding: 20px;
      width: 100%;
      z-index: 1;
    }

    .left_area h3 {
      color: #fff;
      margin: 0px;
      text-transform: uppercase;
      font-size: 22px;
      font-weight: 900;
    }

    .left_area span {
      color: #19B3D3;
    }

    .logout_btn {
      padding: 5px;
      background: #19B3D3;
      text-decoration: none;
      float: right;
      margin-top: -30px;
      margin-right: 40px;
      border-radius: 2px;
      font-size: 15px;
      font-weight: 600;
      color: #fff;
      transition: 0.5s;

    }

    .logout_btn:hover {
      background: #0B87A6;
    }

    .sidebar {
      background: #2f323a;
      margin-top: 70px;
      padding-top: 30px;
      position: fixed;
      left: 0;
      width: 250px;
      height: 100%;
      transition: 0.5s;
      transition-property: left;
    }

    .sidebar .profile_image {
      width: 100px;
      height: 100px;
      border-radius: 100px;
      margin-bottom: 10px;
    }

    .sidebar h4 {
      color: #ccc;
      margin-top: 0;
      
    }

    .sidebar a {
      color: #fff;
      display: block;
      width: 100%;
      line-height: 60px;
      text-decoration: none;
      padding-left: 40px;
      box-sizing: border-box;
      transition: 0.5s;

    }

    .sidebar a:hover {
      background: #19B3D3;
    }

    .sidebar i {
      padding-right: 10px;
    }

    label #sidebar_btn {
      z-index: 1;
      color: #fff;
      position: fixed;
      cursor: pointer;
      left: 300px;
      font-size: 20px;
      margin: 5px 0;
      transition: 0.5s;
      transition-property: color;
    }

    label #sidebar_btn:hover {
      color: #19B3D3;
    }

    #check:checked~.sidebar {
      left: -190px;
    }

    #check:checked~.sidebar a span {
      display: none;
    }

    #check:checked~.sidebar a {
      font-size: 20px;
      margin-left: 170px;
      width: 80px;
    }

    .content {
      margin-left: 250px;
      background: url(background.png) no-repeat;
      background-position: center;
      background-size: cover;
      height: 100vh;
      transition: 0.5s;
    }

    #check:checked~.content {
      margin-left: 60px;
    }

    #check {
      display: none;
    }
  </style>


  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">


</head>

<body>

  <input type="checkbox" id="check">
  <!--header area start-->
  <header>
    <label for="check">
      <i style="left: 200px;margin-top: 17px;"class="fas fa-bars" id="sidebar_btn"></i>
    </label>
    <div class="left_area">
      <h3>Online Quiz</h3>
    </div>
    <div class="right_area">
      <a href="/logout" class="logout_btn">Logout</a>
    </div>
  </header>
  <!--header area end-->
  <!--sidebar start-->
  <div class="sidebar">
    <center>


      <h4>{{request.user.first_name}}</h4>
      <h6 style="color: rgb(255, 255, 255);">( Teacher )</h6>

    </center>

    <a href="{% url 'teacher:teacher-dashboard' %}"><i class="fas fa-tachometer-alt"></i><span>Dashboard</span></a>
    <a href="{% url 'teacher:teacher-exam' %}"><i class="fas fa-book"></i><span>Exam</span></a>
    <a href="{% url 'teacher:teacher-question' %}"><i class="fas fa-question-circle"></i><span>Questions</span></a>
    
  </div>
  <!--sidebar end-->


  <!--content start-->
  <div class="content">
    <br><br><br><br><br>
    {% block content %}

    {% endblock content %}


    <br><br><br>
    {% include "footer.html" %}
  </div>
  <!--content end-->
</body>

</html>

teacher/templates/teacherclick.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <style media="screen">
    .jumbotron {
      margin-top: 0px;
      margin-bottom: 0px;
    }

    .jumbotron h1 {
      text-align: center;
    }

  </style>

</head>

<body>

  {% include "navbar.html" %}
  <br><br>
  <div class="jumbotron" style="margin-bottom:0px;">
    <h1 class="display-4">Teacher login/signup</h1>
    <p class="lead">Welcome to Online Quiz</p>
    <hr class="my-4">
    <p>You can access various features after Login.</p>
    <p class="lead">
      <a class="btn btn-primary btn-lg" href="{% url 'teacher:teachersignup' %}" role="button">Create Your Account</a>
      <a class="btn btn-primary btn-lg" href="{% url 'teacher:teacherlogin' %}" role="button">Login</a>
    </p>
    <br><br><br><br>
  </div>
  {% include "footer.html" %}
</body>

</html>